---
# tasks file for ancillary
- name: Join The Swarm
  become: true
  community.docker.docker_swarm:
    state: join
    advertise_addr: "{{ inventory_hostname }}"
    join_token: "{{ hostvars['deathstar-manager']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ 'deathstar-manager:2377' ]