all: 
  children: 
    manager: 
      hosts: 
        didact: 
    worker: 
      hosts: 
        ancillary: 
  hosts: 
    nginx: 
  vars: 
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_user: jenkins
    docker_users: 
    - username: jenkins
    - username: itzian94
