--- 
all: 
  children: 
    manager: 
      hosts: 
        didact: "10.154.0.37"
    worker: 
      hosts: 
        ancillary: "10.154.0.36"
  hosts: 
    nginx: ~
  vars: 
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_user: jenkins
    docker_users: 
      - 
        username: jenkins
      - 
        username: itzian94
