all:
  hosts:
    nginx:
  children:
    manager:
      hosts:
        didact: '34.89.113.117'
    worker:
      hosts:
        ancillary: '34.89.26.150'
  vars:
    ansible_user: jenkins
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    docker_users:
      - username: jenkins
      - username: itzian94