all:
  hosts:
    nginx:
  children:
    manager:
      hosts:
        didact: 10.154.0.37
    worker:
      hosts:
        ancillary: 10.154.0.36
  vars:
    ansible_user: jenkins
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    docker_users:
      - username: jenkins
      - username: itzian94