---
# tasks file for didact
- name: Init A New Swarm With Default Parameters
  become: true
  community.general.docker_swarm:
    state: present
  register: swarm_info
- name: Print Swarm Info
  debug:
    msg: "{{ swarm_info }}"